### ISSUE TITLE
Front page not working

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/cwp-megaresponsive-pro#3]
I tried but the front page is just not working. Can someone try to reproduce this issue with the latest version on a WordPress 4.1?

@ineagu

**Comment by ineagu** [comment]
@HardeepAsrani can you investigate ? shouldn't be too complicated.

**Comment by HardeepAsrani** [comment]
@ineagu I did and it didn't work for me. But there's always some room for error, so maybe a second opinion the issue can solve it :)

**Comment by ineagu** [comment]
@rodica-andronache do you know anything about this ?

**Comment by mariusghitulescu** [comment]
Static Frontpage is not working. Default "Latest Posts" is working.

**Comment by ineagu** [comment]
@claudiuvertistudio can you please investigate and fix this ?

**Comment by ineagu** [comment]
@claudiuvertistudio please fix this also tomorrow.

**Comment by claudiuvertistudio** [comment]
@HardeepAsrani, @mariusghitulescu please check if it's ok now.
