### ISSUE TITLE
Invalid Key in Child Theme

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/cwp-megaresponsive-pro#4]
License key isn't working on the child theme.

**Comment by HardeepAsrani** [comment]
Hey there. :) @ineagu

**Comment by selu91** [comment]
@HardeepAsrani i have tested and is working. How did you test it?

**Comment by HardeepAsrani** [comment]
I didn't, but a customer reported it, so I checked the ticket which was
still open. :/

Regards,
Hardeep Asrani
